# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.13.1

pipelines:
  default:
    - step:
        deployment: test
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run dist
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/dist" --form files=@"SewerWatchDesktop-0.0.1.dmg" "SewerWatchDesktop Setup 0.0.1.exe" "SewerWatchDesktop-0.0.1.AppImage"
          